#164393448 Configure eslint using airbnb config
PSIFON/my-event-place pull request #4
Opened 2019-03-14 16:13 UTC by pmndifon

#### What does this PR do?
- Add eslint airnbnb configuration

#### Description of Task to be completed?
- Install eslint, eslint-config-airbnb-base and eslint-plugin-import

#### How should this be manually tested?
- Not yet implemented

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
#164393448

#### Screenshots (if appropriate)
none

#### Questions:
How do i add an eslint script to package.json

2019-03-14 19:40 UTC, jundelikwo requested changes

2019-03-14 19:40 UTC, jundelikwo commented on .eslintrc.js
> +    "extends": ["airbnb", "eslint:recommended"],
@pmndifon Change it to this
`"extends": ["eslint:recommended","airbnb"],`

2019-03-16 11:17 UTC, jundelikwo approved these changes
Excellent work @pmndifon

2019-03-16 16:01 UTC, davidshare approved these changes
Well done Patrick

2019-03-20 16:31 UTC, Danielshow approved these changes
Nice one @pmndifon, LGTM

2019-03-20 18:47 UTC, merged